# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master", "dev-puma90", "Mike-changes" ]
  pull_request:
    branches: [ "master", "dev-puma90", "Mike-changes" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Clean app
      run: dotnet clean tiempo-libre.app/tiempo-libre.csproj
    - name: Restore dependencies for app
      run: dotnet restore tiempo-libre.app/tiempo-libre.csproj
    - name: Build app
      run: dotnet build --no-restore tiempo-libre.app/tiempo-libre.csproj --configuration Release
    - name: Clean tests
      run: dotnet clean tiempo-libre.Tests/tiempo-libre.Tests.csproj
    - name: Restore dependencies for tests
      run: dotnet restore tiempo-libre.Tests/tiempo-libre.Tests.csproj
    - name: Test
      run: dotnet test tiempo-libre.Tests/tiempo-libre.Tests.csproj --verbosity detailed
