version: '3.8'

services:
  # Servicio para la API de .NET
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
      - "5055:5055"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5050
      - ConnectionStrings__DefaultConnection=Server=db;Database=${DB_NAME};User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True
    depends_on:
      - db

  # Servicio para la base de datos SQL Server
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD} # La contrase√±a se toma de la variable de entorno
    ports:
      - "1433:1433" # Mapea el puerto de SQL Server
    volumes:
      - sql-server-data:/var/opt/mssql

volumes:
  sql-server-data: # Volumen para persistir los datos de la BD
